apiVersion: apps/v1
kind: Deployment
metadata:
  name: good-deployment-latesttag
  labels:
    app: busybox
  namespace: kyverno-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busybox
  template:
    metadata:
      labels:
        app: busybox
    spec:
      containers:
      - image: docker.io/bitnami/apache:2.4
        name: busybox
        securityContext:
          runAsNonRoot: true
        command: ["sleep", "9999"]
        resources:
          requests:
            memory: "256Mi"
            cpu: "0.5"
          limits:
            memory: "256Mi"
            cpu: "1"
