---
apiVersion: v1
kind: Pod
metadata:
  name: badpod-restrict-seccomp-strict
  namespace: kyverno-test
spec:
  containers:
  - name: container01
    image: busybox
    command:
    - "sleep"
    - "3600"
  securityContext:
    seccompProfile:
      type: Unconfined
