###### Pods - Good
apiVersion: v1
kind: Pod
metadata:
  name: goodpod01-disallow-capabilities 
  namespace: kyverno-test
spec:
  containers:
  - name: container01
    image: busybox
    command:
    - "sleep"
    - "3600"