apiVersion: v1
kind: Pod
metadata:
  name: badpod-disallow-privilege-escalation
  namespace: kyverno-test
spec:
  containers:
  - name: container01
    image: busybox
    command:
    - "sleep"
    - "3600"
    securityContext:
      allowPrivilegeEscalation: true
