apiVersion: v1
kind: Pod
metadata:
  name: goodpod02-disallow-privileged-containers 
  namespace: kyverno-test
spec:
  containers:
  - name: container01
    image: busybox
    command:
    - "sleep"
    - "3600"
