---
apiVersion: v1
kind: Pod
metadata:
  name: badpod-disallow-host-namespaces
  namespace: kyverno-test
spec:
  hostPID: true
  hostIPC: true
  hostNetwork: true
  containers:
  - name: container01
    image: busybox
    command:
    - "sleep"
    - "3600"
