apiVersion: v1
kind: Pod
metadata:
  name: goodpod02
  namespace: kyverno-test
spec:
  containers:
  - name: container01
    image: httpd
    volumeMounts:
      - name: temp
        mountPath: /scratch
  volumes:
  - name: temp
    emptyDir: {}
